// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: github.com/amazingchow/photon-dance-wal/walpb/record.proto

package walpb

import (
	_ "github.com/amazingchow/photon-dance-wal/walpb/gogoproto"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *int64  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Crc  *uint32 `protobuf:"varint,2,opt,name=crc" json:"crc,omitempty"`
	Data []byte  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetType() int64 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *Record) GetCrc() uint32 {
	if x != nil && x.Crc != nil {
		return *x.Crc
	}
	return 0
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index *uint64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Term  *uint64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *Snapshot) GetTerm() uint64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  *int64  `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Index *uint64 `protobuf:"varint,2,opt,name=Index" json:"Index,omitempty"` // must be 64-bit aligned for atomic operations
	Data  []byte  `protobuf:"bytes,3,opt,name=Data" json:"Data,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetType() int64 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_amazingchow_photon_dance_wal_walpb_record_proto protoreflect.FileDescriptor

var file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x77, 0x61, 0x6c, 0x2f, 0x77, 0x61, 0x6c, 0x70, 0x62, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x77, 0x61,
	0x6c, 0x70, 0x62, 0x1a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x6e, 0x2d, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x77, 0x61, 0x6c, 0x2f, 0x77, 0x61, 0x6c,
	0x70, 0x62, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x18, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x63,
	0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x03,
	0x63, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x18, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x04, 0xc8,
	0xde, 0x1f, 0x00, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x51, 0x0a, 0x05, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x18, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x05,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x04, 0xc8, 0xde, 0x1f,
	0x00, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x3f, 0x5a, 0x2d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61, 0x7a, 0x69,
	0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d, 0x64, 0x61,
	0x6e, 0x63, 0x65, 0x2d, 0x77, 0x61, 0x6c, 0x2f, 0x77, 0x61, 0x6c, 0x70, 0x62, 0xc8, 0xe2, 0x1e,
	0x01, 0xe0, 0xe2, 0x1e, 0x01, 0xd0, 0xe2, 0x1e, 0x01, 0xc8, 0xe1, 0x1e, 0x00,
}

var (
	file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescOnce sync.Once
	file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescData = file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDesc
)

func file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescGZIP() []byte {
	file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescOnce.Do(func() {
		file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescData)
	})
	return file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDescData
}

var file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_goTypes = []interface{}{
	(*Record)(nil),   // 0: walpb.Record
	(*Snapshot)(nil), // 1: walpb.Snapshot
	(*Entry)(nil),    // 2: walpb.Entry
}
var file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_init() }
func file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_init() {
	if File_github_com_amazingchow_photon_dance_wal_walpb_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_goTypes,
		DependencyIndexes: file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_depIdxs,
		MessageInfos:      file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_msgTypes,
	}.Build()
	File_github_com_amazingchow_photon_dance_wal_walpb_record_proto = out.File
	file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_rawDesc = nil
	file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_goTypes = nil
	file_github_com_amazingchow_photon_dance_wal_walpb_record_proto_depIdxs = nil
}
